# Generated by Django 5.1.2 on 2025-10-08 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(default='confirmado', max_length=50)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(default='confirmado', max_length=50)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sala')),
            ],
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
